"""create versioned place materials

Revision ID: 28388488c1fd
Revises: e14eff9a3f10
Create Date: 2026-09-04 09:37:13.064388

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28388488c1fd"
down_revision: str | Sequence[str] | None = "e14eff9a3f10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "materials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("place_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "text",
                "external_link",
                "image",
                "video",
                "audio",
                name="material_type",
                native_enum=False,
                create_constraint=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review",
                "published",
                "rejected",
                "archived",
                name="moderation_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="pending_review",
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(btrim(title)) > 0", name="ck_materials_title_not_blank"
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'published', 'rejected', 'archived')",
            name="ck_materials_status",
        ),
        sa.CheckConstraint(
            "type IN ('text', 'external_link', 'image', 'video', 'audio')",
            name="ck_materials_type",
        ),
        sa.ForeignKeyConstraint(
            ["place_id"],
            ["app.places.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="app",
    )
    op.create_index(
        "idx_materials_place_status",
        "materials",
        ["place_id", "status"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "material_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_review",
                "published",
                "rejected",
                "archived",
                name="moderation_status",
                native_enum=False,
                create_constraint=False,
            ),
            server_default="pending_review",
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "url IS NULL OR url ~* '^https?://'", name="ck_material_revisions_http_url"
        ),
        sa.CheckConstraint(
            "(content IS NOT NULL) <> (url IS NOT NULL)",
            name="ck_material_revisions_exactly_one_value",
        ),
        sa.CheckConstraint(
            "content IS NULL OR char_length(btrim(content)) > 0",
            name="ck_material_revisions_content_not_blank",
        ),
        sa.CheckConstraint(
            "revision_number > 0", name="ck_material_revisions_number_positive"
        ),
        sa.CheckConstraint(
            "status IN ('pending_review', 'published', 'rejected', 'archived')",
            name="ck_material_revisions_status",
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["app.materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "material_id",
            "revision_number",
            name="uq_material_revisions_material_number",
        ),
        schema="app",
    )
    op.create_index(
        "idx_material_revisions_material_status_number",
        "material_revisions",
        ["material_id", "status", "revision_number"],
        unique=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_material_revisions_material_status_number",
        table_name="material_revisions",
        schema="app",
        if_exists=True,
    )
    op.drop_table("material_revisions", schema="app")
    op.drop_index("idx_materials_place_status", table_name="materials", schema="app")
    op.drop_table("materials", schema="app")
    # ### end Alembic commands ###
